
import "./globals.css";
import {cn} from "@/lib/utils";
import Navbar from "@/components/layout/navbar";
import {inter, poppins} from "@/assests/fonts";
import {ConvexClientProvider} from "@/providers/ConvexClientProvider";
import WeaponAlertDialog from "@/components/WeaponAlertDialog";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={cn("antialiased bg-gray-900 text-white", poppins.className)}>
                <ConvexClientProvider>
                    <main className={"px-4 flex flex-col"}>
                        <Navbar />
                        {children}
                        <WeaponAlertDialog />
                    </main>
                </ConvexClientProvider>
            </body>
        </html>
    );
}
